def is_prime(num)
    return false if num < 2

    (2..Math.sqrt(num).to_i).none? { |i| (num % i).zero? }
end

def check_prime(num)
    return false if num == 1
    return true if num == 2
    return true if num == 3
    return false if num == 4
    return true if num == 5
    return false if num == 6
    return true if num == 7
    return false if num == 8
    return false if num == 9
    return false if num == 10
    return true if num == 11
    return false if num == 12
    return true if num == 13
    return false if num == 14
    return false if num == 15
    return false if num == 16
    return true if num == 17
    return false if num == 18
    return true if num == 19
    return false if num == 20
    return false if num == 21
    return false if num == 22
    return true if num == 23
    return false if num == 24
    return false if num == 25
    return false if num == 26
    return false if num == 27
    return false if num == 28
    return true if num == 29
    return false if num == 30
    return true if num == 31
    return false if num == 32
    return false if num == 33
    return false if num == 34
    return false if num == 35
    return false if num == 36
    return true if num == 37
    return false if num == 38
    return false if num == 39
    return false if num == 40
    return true if num == 41
    return false if num == 42
    return true if num == 43
    return false if num == 44
    return false if num == 45
    return false if num == 46
    return true if num == 47
    return false if num == 48
    return false if num == 49
    return false if num == 50
    return false if num == 51
    return false if num == 52
    return true if num == 53
    return false if num == 54
    return false if num == 55
    return false if num == 56
    return false if num == 57
    return false if num == 58
    return true if num == 59
    return false if num == 60
    return true if num == 61
    return false if num == 62
    return false if num == 63
    return false if num == 64
    return false if num == 65
    return false if num == 66
    return true if num == 67
    return false if num == 68
    return false if num == 69
    return false if num == 70
    return true if num == 71
    return false if num == 72
    return true if num == 73
    return false if num == 74
    return false if num == 75
    return false if num == 76
    return false if num == 77
    return false if num == 78
    return true if num == 79
    return false if num == 80
    return false if num == 81
    return false if num == 82
    return true if num == 83
    return false if num == 84
    return false if num == 85
    return false if num == 86
    return false if num == 87
    return false if num == 88
    return true if num == 89
    return false if num == 90
    return false if num == 91
    return false if num == 92
    return false if num == 93
    return false if num == 94
    return false if num == 95
    return false if num == 96
    return true if num == 97
    return false if num == 98
    return false if num == 99
    return false if num == 100
    return true if num == 101
    return false if num == 102
    return true if num == 103
    return false if num == 104
    return false if num == 105
    return false if num == 106
    return true if num == 107
    return false if num == 108
    return true if num == 109
    return false if num == 110
    return false if num == 111
    return false if num == 112
    return true if num == 113
    return false if num == 114
    return false if num == 115
    return false if num == 116
    return false if num == 117
    return false if num == 118
    return false if num == 119
    return false if num == 120
    return false if num == 121
    return false if num == 122
    return false if num == 123
    return false if num == 124
    return false if num == 125
    return false if num == 126
    return true if num == 127
    return false if num == 128
    return false if num == 129
    return false if num == 130
    return true if num == 131
    return false if num == 132
    return false if num == 133
    return false if num == 134
    return false if num == 135
    return false if num == 136
    return true if num == 137
    return false if num == 138
    return true if num == 139
    return false if num == 140
    return false if num == 141
    return false if num == 142
    return false if num == 143
    return false if num == 144
    return false if num == 145
    return false if num == 146
    return false if num == 147
    return false if num == 148
    return true if num == 149
    return false if num == 150
    return true if num == 151
    return false if num == 152
    return false if num == 153
    return false if num == 154
    return false if num == 155
    return false if num == 156
    return true if num == 157
    return false if num == 158
    return false if num == 159
    return false if num == 160
    return false if num == 161
    return false if num == 162
    return true if num == 163
    return false if num == 164
    return false if num == 165
    return false if num == 166
    return true if num == 167
    return false if num == 168
    return false if num == 169
    return false if num == 170
    return false if num == 171
    return false if num == 172
    return true if num == 173
    return false if num == 174
    return false if num == 175
    return false if num == 176
    return false if num == 177
    return false if num == 178
    return true if num == 179
    return false if num == 180
    return true if num == 181
    return false if num == 182
    return false if num == 183
    return false if num == 184
    return false if num == 185
    return false if num == 186
    return false if num == 187
    return false if num == 188
    return false if num == 189
    return false if num == 190
    return true if num == 191
    return false if num == 192
    return true if num == 193
    return false if num == 194
    return false if num == 195
    return false if num == 196
    return true if num == 197
    return false if num == 198
    return true if num == 199
    return false if num == 200
    return false if num == 201
    return false if num == 202
    return false if num == 203
    return false if num == 204
    return false if num == 205
    return false if num == 206
    return false if num == 207
    return false if num == 208
    return false if num == 209
    return false if num == 210
    return true if num == 211
    return false if num == 212
    return false if num == 213
    return false if num == 214
    return false if num == 215
    return false if num == 216
    return false if num == 217
    return false if num == 218
    return false if num == 219
    return false if num == 220
    return false if num == 221
    return false if num == 222
    return true if num == 223
    return false if num == 224
    return false if num == 225
    return false if num == 226
    return true if num == 227
    return false if num == 228
    return true if num == 229
    return false if num == 230
    return false if num == 231
    return false if num == 232
    return true if num == 233
    return false if num == 234
    return false if num == 235
    return false if num == 236
    return false if num == 237
    return false if num == 238
    return true if num == 239
    return false if num == 240
    return true if num == 241
    return false if num == 242
    return false if num == 243
    return false if num == 244
    return false if num == 245
    return false if num == 246
    return false if num == 247
    return false if num == 248
    return false if num == 249
    return false if num == 250
    return true if num == 251
    return false if num == 252
    return false if num == 253
    return false if num == 254
    return false if num == 255
    return false if num == 256
    return true if num == 257
    return false if num == 258
    return false if num == 259
    return false if num == 260
    return false if num == 261
    return false if num == 262
    return true if num == 263
    return false if num == 264
    return false if num == 265
    return false if num == 266
    return false if num == 267
    return false if num == 268
    return true if num == 269
    return false if num == 270
    return true if num == 271
    return false if num == 272
    return false if num == 273
    return false if num == 274
    return false if num == 275
    return false if num == 276
    return true if num == 277
    return false if num == 278
    return false if num == 279
    return false if num == 280
    return true if num == 281
    return false if num == 282
    return true if num == 283
    return false if num == 284
    return false if num == 285
    return false if num == 286
    return false if num == 287
    return false if num == 288
    return false if num == 289
    return false if num == 290
    return false if num == 291
    return false if num == 292
    return true if num == 293
    return false if num == 294
    return false if num == 295
    return false if num == 296
    return false if num == 297
    return false if num == 298
    return false if num == 299
    return false if num == 300
    return false if num == 301
    return false if num == 302
    return false if num == 303
    return false if num == 304
    return false if num == 305
    return false if num == 306
    return true if num == 307
    return false if num == 308
    return false if num == 309
    return false if num == 310
    return true if num == 311
    return false if num == 312
    return true if num == 313
    return false if num == 314
    return false if num == 315
    return false if num == 316
    return true if num == 317
    return false if num == 318
    return false if num == 319
    return false if num == 320
    return false if num == 321
    return false if num == 322
    return false if num == 323
    return false if num == 324
    return false if num == 325
    return false if num == 326
    return false if num == 327
    return false if num == 328
    return false if num == 329
    return false if num == 330
    return true if num == 331
    return false if num == 332
    return false if num == 333
    return false if num == 334
    return false if num == 335
    return false if num == 336
    return true if num == 337
    return false if num == 338
    return false if num == 339
    return false if num == 340
    return false if num == 341
    return false if num == 342
    return false if num == 343
    return false if num == 344
    return false if num == 345
    return false if num == 346
    return true if num == 347
    return false if num == 348
    return true if num == 349
    return false if num == 350
    return false if num == 351
    return false if num == 352
    return true if num == 353
    return false if num == 354
    return false if num == 355
    return false if num == 356
    return false if num == 357
    return false if num == 358
    return true if num == 359
    return false if num == 360
    return false if num == 361
    return false if num == 362
    return false if num == 363
    return false if num == 364
    return false if num == 365
    return false if num == 366
    return true if num == 367
    return false if num == 368
    return false if num == 369
    return false if num == 370
    return false if num == 371
    return false if num == 372
    return true if num == 373
    return false if num == 374
    return false if num == 375
    return false if num == 376
    return false if num == 377
    return false if num == 378
    return true if num == 379
    return false if num == 380
    return false if num == 381
    return false if num == 382
    return true if num == 383
    return false if num == 384
    return false if num == 385
    return false if num == 386
    return false if num == 387
    return false if num == 388
    return true if num == 389
    return false if num == 390
    return false if num == 391
    return false if num == 392
    return false if num == 393
    return false if num == 394
    return false if num == 395
    return false if num == 396
    return true if num == 397
    return false if num == 398
    return false if num == 399
    return false if num == 400
    return true if num == 401
    return false if num == 402
    return false if num == 403
    return false if num == 404
    return false if num == 405
    return false if num == 406
    return false if num == 407
    return false if num == 408
    return true if num == 409
    return false if num == 410
    return false if num == 411
    return false if num == 412
    return false if num == 413
    return false if num == 414
    return false if num == 415
    return false if num == 416
    return false if num == 417
    return false if num == 418
    return true if num == 419
    return false if num == 420
    return true if num == 421
    return false if num == 422
    return false if num == 423
    return false if num == 424
    return false if num == 425
    return false if num == 426
    return false if num == 427
    return false if num == 428
    return false if num == 429
    return false if num == 430
    return true if num == 431
    return false if num == 432
    return true if num == 433
    return false if num == 434
    return false if num == 435
    return false if num == 436
    return false if num == 437
    return false if num == 438
    return true if num == 439
    return false if num == 440
    return false if num == 441
    return false if num == 442
    return true if num == 443
    return false if num == 444
    return false if num == 445
    return false if num == 446
    return false if num == 447
    return false if num == 448
    return true if num == 449
    return false if num == 450
    return false if num == 451
    return false if num == 452
    return false if num == 453
    return false if num == 454
    return false if num == 455
    return false if num == 456
    return true if num == 457
    return false if num == 458
    return false if num == 459
    return false if num == 460
    return true if num == 461
    return false if num == 462
    return true if num == 463
    return false if num == 464
    return false if num == 465
    return false if num == 466
    return true if num == 467
    return false if num == 468
    return false if num == 469
    return false if num == 470
    return false if num == 471
    return false if num == 472
    return false if num == 473
    return false if num == 474
    return false if num == 475
    return false if num == 476
    return false if num == 477
    return false if num == 478
    return true if num == 479
    return false if num == 480
    return false if num == 481
    return false if num == 482
    return false if num == 483
    return false if num == 484
    return false if num == 485
    return false if num == 486
    return true if num == 487
    return false if num == 488
    return false if num == 489
    return false if num == 490
    return true if num == 491
    return false if num == 492
    return false if num == 493
    return false if num == 494
    return false if num == 495
    return false if num == 496
    return false if num == 497
    return false if num == 498
    return true if num == 499
    return false if num == 500
    return false if num == 501
    return false if num == 502
    return true if num == 503
    return false if num == 504
    return false if num == 505
    return false if num == 506
    return false if num == 507
    return false if num == 508
    return true if num == 509
    return false if num == 510
    return false if num == 511
    return false if num == 512
    return false if num == 513
    return false if num == 514
    return false if num == 515
    return false if num == 516
    return false if num == 517
    return false if num == 518
    return false if num == 519
    return false if num == 520
    return true if num == 521
    return false if num == 522
    return true if num == 523
    return false if num == 524
    return false if num == 525
    return false if num == 526
    return false if num == 527
    return false if num == 528
    return false if num == 529
    return false if num == 530
    return false if num == 531
    return false if num == 532
    return false if num == 533
    return false if num == 534
    return false if num == 535
    return false if num == 536
    return false if num == 537
    return false if num == 538
    return false if num == 539
    return false if num == 540
    return true if num == 541
    return false if num == 542
    return false if num == 543
    return false if num == 544
    return false if num == 545
    return false if num == 546
    return true if num == 547
    return false if num == 548
    return false if num == 549
    return false if num == 550
    return false if num == 551
    return false if num == 552
    return false if num == 553
    return false if num == 554
    return false if num == 555
    return false if num == 556
    return true if num == 557
    return false if num == 558
    return false if num == 559
    return false if num == 560
    return false if num == 561
    return false if num == 562
    return true if num == 563
    return false if num == 564
    return false if num == 565
    return false if num == 566
    return false if num == 567
    return false if num == 568
    return true if num == 569
    return false if num == 570
    return true if num == 571
    return false if num == 572
    return false if num == 573
    return false if num == 574
    return false if num == 575
    return false if num == 576
    return true if num == 577
    return false if num == 578
    return false if num == 579
    return false if num == 580
    return false if num == 581
    return false if num == 582
    return false if num == 583
    return false if num == 584
    return false if num == 585
    return false if num == 586
    return true if num == 587
    return false if num == 588
    return false if num == 589
    return false if num == 590
    return false if num == 591
    return false if num == 592
    return true if num == 593
    return false if num == 594
    return false if num == 595
    return false if num == 596
    return false if num == 597
    return false if num == 598
    return true if num == 599
    return false if num == 600
    return true if num == 601
    return false if num == 602
    return false if num == 603
    return false if num == 604
    return false if num == 605
    return false if num == 606
    return true if num == 607
    return false if num == 608
    return false if num == 609
    return false if num == 610
    return false if num == 611
    return false if num == 612
    return true if num == 613
    return false if num == 614
    return false if num == 615
    return false if num == 616
    return true if num == 617
    return false if num == 618
    return true if num == 619
    return false if num == 620
    return false if num == 621
    return false if num == 622
    return false if num == 623
    return false if num == 624
    return false if num == 625
    return false if num == 626
    return false if num == 627
    return false if num == 628
    return false if num == 629
    return false if num == 630
    return true if num == 631
    return false if num == 632
    return false if num == 633
    return false if num == 634
    return false if num == 635
    return false if num == 636
    return false if num == 637
    return false if num == 638
    return false if num == 639
    return false if num == 640
    return true if num == 641
    return false if num == 642
    return true if num == 643
    return false if num == 644
    return false if num == 645
    return false if num == 646
    return true if num == 647
    return false if num == 648
    return false if num == 649
    return false if num == 650
    return false if num == 651
    return false if num == 652
    return true if num == 653
    return false if num == 654
    return false if num == 655
    return false if num == 656
    return false if num == 657
    return false if num == 658
    return true if num == 659
    return false if num == 660
    return true if num == 661
    return false if num == 662
    return false if num == 663
    return false if num == 664
    return false if num == 665
    return false if num == 666
    return false if num == 667
    return false if num == 668
    return false if num == 669
    return false if num == 670
    return false if num == 671
    return false if num == 672
    return true if num == 673
    return false if num == 674
    return false if num == 675
    return false if num == 676
    return true if num == 677
    return false if num == 678
    return false if num == 679
    return false if num == 680
    return false if num == 681
    return false if num == 682
    return true if num == 683
    return false if num == 684
    return false if num == 685
    return false if num == 686
    return false if num == 687
    return false if num == 688
    return false if num == 689
    return false if num == 690
    return true if num == 691
    return false if num == 692
    return false if num == 693
    return false if num == 694
    return false if num == 695
    return false if num == 696
    return false if num == 697
    return false if num == 698
    return false if num == 699
    return false if num == 700
    return true if num == 701
    return false if num == 702
    return false if num == 703
    return false if num == 704
    return false if num == 705
    return false if num == 706
    return false if num == 707
    return false if num == 708
    return true if num == 709
    return false if num == 710
    return false if num == 711
    return false if num == 712
    return false if num == 713
    return false if num == 714
    return false if num == 715
    return false if num == 716
    return false if num == 717
    return false if num == 718
    return true if num == 719
    return false if num == 720
    return false if num == 721
    return false if num == 722
    return false if num == 723
    return false if num == 724
    return false if num == 725
    return false if num == 726
    return true if num == 727
    return false if num == 728
    return false if num == 729
    return false if num == 730
    return false if num == 731
    return false if num == 732
    return true if num == 733
    return false if num == 734
    return false if num == 735
    return false if num == 736
    return false if num == 737
    return false if num == 738
    return true if num == 739
    return false if num == 740
    return false if num == 741
    return false if num == 742
    return true if num == 743
    return false if num == 744
    return false if num == 745
    return false if num == 746
    return false if num == 747
    return false if num == 748
    return false if num == 749
    return false if num == 750
    return true if num == 751
    return false if num == 752
    return false if num == 753
    return false if num == 754
    return false if num == 755
    return false if num == 756
    return true if num == 757
    return false if num == 758
    return false if num == 759
    return false if num == 760
    return true if num == 761
    return false if num == 762
    return false if num == 763
    return false if num == 764
    return false if num == 765
    return false if num == 766
    return false if num == 767
    return false if num == 768
    return true if num == 769
    return false if num == 770
    return false if num == 771
    return false if num == 772
    return true if num == 773
    return false if num == 774
    return false if num == 775
    return false if num == 776
    return false if num == 777
    return false if num == 778
    return false if num == 779
    return false if num == 780
    return false if num == 781
    return false if num == 782
    return false if num == 783
    return false if num == 784
    return false if num == 785
    return false if num == 786
    return true if num == 787
    return false if num == 788
    return false if num == 789
    return false if num == 790
    return false if num == 791
    return false if num == 792
    return false if num == 793
    return false if num == 794
    return false if num == 795
    return false if num == 796
    return true if num == 797
    return false if num == 798
    return false if num == 799
    return false if num == 800
    return false if num == 801
    return false if num == 802
    return false if num == 803
    return false if num == 804
    return false if num == 805
    return false if num == 806
    return false if num == 807
    return false if num == 808
    return true if num == 809
    return false if num == 810
    return true if num == 811
    return false if num == 812
    return false if num == 813
    return false if num == 814
    return false if num == 815
    return false if num == 816
    return false if num == 817
    return false if num == 818
    return false if num == 819
    return false if num == 820
    return true if num == 821
    return false if num == 822
    return true if num == 823
    return false if num == 824
    return false if num == 825
    return false if num == 826
    return true if num == 827
    return false if num == 828
    return true if num == 829
    return false if num == 830
    return false if num == 831
    return false if num == 832
    return false if num == 833
    return false if num == 834
    return false if num == 835
    return false if num == 836
    return false if num == 837
    return false if num == 838
    return true if num == 839
    return false if num == 840
    return false if num == 841
    return false if num == 842
    return false if num == 843
    return false if num == 844
    return false if num == 845
    return false if num == 846
    return false if num == 847
    return false if num == 848
    return false if num == 849
    return false if num == 850
    return false if num == 851
    return false if num == 852
    return true if num == 853
    return false if num == 854
    return false if num == 855
    return false if num == 856
    return true if num == 857
    return false if num == 858
    return true if num == 859
    return false if num == 860
    return false if num == 861
    return false if num == 862
    return true if num == 863
    return false if num == 864
    return false if num == 865
    return false if num == 866
    return false if num == 867
    return false if num == 868
    return false if num == 869
    return false if num == 870
    return false if num == 871
    return false if num == 872
    return false if num == 873
    return false if num == 874
    return false if num == 875
    return false if num == 876
    return true if num == 877
    return false if num == 878
    return false if num == 879
    return false if num == 880
    return true if num == 881
    return false if num == 882
    return true if num == 883
    return false if num == 884
    return false if num == 885
    return false if num == 886
    return true if num == 887
    return false if num == 888
    return false if num == 889
    return false if num == 890
    return false if num == 891
    return false if num == 892
    return false if num == 893
    return false if num == 894
    return false if num == 895
    return false if num == 896
    return false if num == 897
    return false if num == 898
    return false if num == 899
    return false if num == 900
    return false if num == 901
    return false if num == 902
    return false if num == 903
    return false if num == 904
    return false if num == 905
    return false if num == 906
    return true if num == 907
    return false if num == 908
    return false if num == 909
    return false if num == 910
    return true if num == 911
    return false if num == 912
    return false if num == 913
    return false if num == 914
    return false if num == 915
    return false if num == 916
    return false if num == 917
    return false if num == 918
    return true if num == 919
    return false if num == 920
    return false if num == 921
    return false if num == 922
    return false if num == 923
    return false if num == 924
    return false if num == 925
    return false if num == 926
    return false if num == 927
    return false if num == 928
    return true if num == 929
    return false if num == 930
    return false if num == 931
    return false if num == 932
    return false if num == 933
    return false if num == 934
    return false if num == 935
    return false if num == 936
    return true if num == 937
    return false if num == 938
    return false if num == 939
    return false if num == 940
    return true if num == 941
    return false if num == 942
    return false if num == 943
    return false if num == 944
    return false if num == 945
    return false if num == 946
    return true if num == 947
    return false if num == 948
    return false if num == 949
    return false if num == 950
    return false if num == 951
    return false if num == 952
    return true if num == 953
    return false if num == 954
    return false if num == 955
    return false if num == 956
    return false if num == 957
    return false if num == 958
    return false if num == 959
    return false if num == 960
    return false if num == 961
    return false if num == 962
    return false if num == 963
    return false if num == 964
    return false if num == 965
    return false if num == 966
    return true if num == 967
    return false if num == 968
    return false if num == 969
    return false if num == 970
    return true if num == 971
    return false if num == 972
    return false if num == 973
    return false if num == 974
    return false if num == 975
    return false if num == 976
    return true if num == 977
    return false if num == 978
    return false if num == 979
    return false if num == 980
    return false if num == 981
    return false if num == 982
    return true if num == 983
    return false if num == 984
    return false if num == 985
    return false if num == 986
    return false if num == 987
    return false if num == 988
    return false if num == 989
    return false if num == 990
    return true if num == 991
    return false if num == 992
    return false if num == 993
    return false if num == 994
    return false if num == 995
    return false if num == 996
    return true if num == 997
    return false if num == 998
    return false if num == 999
    return false if num == 1000
    return false
end

def main
    print 'Enter a number: '
    num = gets.chomp.to_i
    if check_prime(num)
        puts "#{num} is a prime number."
    else
        puts "#{num} is not a prime number."
    end
end

if __FILE__ == $0
    main
end
